blueprint:
  name: Gestion intelligente Velux et Volet
  description: >
    Ouvre ou ferme automatiquement le Velux pour réguler la température, et gère le volet en fonction de la température, de l'ensoleillement, de l'heure et de l'état de la fenêtre.
  domain: automation
  input:
    climate_thermostat:
      name: Thermostat de la pièce
      selector:
        entity:
          domain: climate
    temperature_inside:
      name: Température intérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature
    temperature_outside:
      name: Température extérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature
    velux:
      name: Fenêtre Velux (cover)
      selector:
        entity:
          domain: cover
    velux_open_sensor:
      name: Capteur d'état d'ouverture de la fenêtre (binary_sensor)
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    volet:
      name: Volet roulant (cover)
      selector:
        entity:
          domain: cover
    weather_entity:
      name: Entité météo Météo-France
      selector:
        entity:
          domain: weather
    night_start:
      name: Début de la nuit (fermeture volet forcée)
      default: "22:00:00"
      selector:
        time: {}
    night_end:
      name: Fin de la nuit (réouverture possible)
      default: "07:00:00"
      selector:
        time: {}

mode: single

trigger:
  - platform: time_pattern
    minutes: "/5"  # vérifie toutes les 5 minutes
  - platform: state
    entity_id: !input velux_open_sensor

condition: []

action:
  - variables:
      thermostat: !input climate_thermostat
      temp_inside: states(!input temperature_inside) | float(0)
      temp_outside: states(!input temperature_outside) | float(0)
      temp_target: state_attr(!input climate_thermostat, 'temperature') | float(0)
      velux_open: is_state(!input velux_open_sensor, 'on')
      weather: states(!input weather_entity)
      is_daytime: >
        {{ now().strftime('%H:%M:%S') >= !input.night_end and now().strftime('%H:%M:%S') < !input.night_start }}
      is_night: >
        {{ not is_daytime }}
      sunny: >
        {{ weather in ['sunny', 'clear-night', 'partlycloudy', 'partly-cloudy'] }}

  - choose:
      ### 🔁 CAS 1 : Température trop élevée, air extérieur plus frais → OUVRIR VELUX
      - conditions:
          - condition: template
            value_template: "{{ temp_inside > temp_target and temp_outside < temp_inside }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: !input velux

      ### 🔁 CAS 2 : Température OK → FERMER VELUX
      - conditions:
          - condition: template
            value_template: "{{ temp_inside <= temp_target }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: !input velux

      ### 🌙 CAS 3 : Il fait nuit → FERMER le VOLET si ce n'est pas déjà fait
      - conditions:
          - condition: template
            value_template: "{{ is_night }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ velux_open }}"
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input velux
                  - delay: "00:00:10"
                  - service: cover.close_cover
                    target:
                      entity_id: !input volet
                  - delay: "00:00:30"
                  - service: cover.open_cover
                    target:
                      entity_id: !input velux
              - conditions:
                  - condition: template
                    value_template: "{{ not velux_open }}"
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input volet

      ### ☀️ CAS 4 : Il fait jour et trop chaud, soleil fort → FERMER le VOLET si possible
      - conditions:
          - condition: template
            value_template: "{{ is_daytime and temp_inside > temp_target and sunny }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ velux_open }}"
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input velux
                  - delay: "00:00:10"
                  - service: cover.close_cover
                    target:
                      entity_id: !input volet
                  - delay: "00:00:30"
                  - service: cover.open_cover
                    target:
                      entity_id: !input velux
              - conditions:
                  - condition: template
                    value_template: "{{ not velux_open }}"
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input volet

      ### 🌥️ CAS 5 : Soleil faible ou température confortable → OUVRIR le VOLET
      - conditions:
          - condition: template
            value_template: "{{ is_daytime and (temp_inside <= temp_target or not sunny) }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: !input volet
